directories:
  output: dist-electron
  buildResources: build
appId: com.floridaburgers.pos
productName: Florida Burgers POS
copyright: Florida Burgers 2025
asar: true
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
portable:
  artifactName: FloridaBurgersPOS-portable.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Florida Burgers POS
  perMachine: false
forceCodeSigning: false
electronVersion: 29.4.6
